deluge:
  image: binhex/arch-delugevpn:latest
  container_name: deluge
  restart: always
  cap_add:
    - NET_ADMIN
  ports:
    - 8112:8112
    - 8118:8118
    - 58846:58846
    - 58946:58946
  environment:
    - PUID=1001
    - PGID=33
    - VPN_ENABLED=yes
    - VPN_PROV=airvpn
    - ENABLE_PRIVOXY=yes
    - LAN_NETWORK=192.168.1.0/24
    - NAME_SERVERS=209.222.18.222,37.235.1.174,8.8.8.8,209.222.18.218,37.235.1.177,8.8.4.4
    - UMASK=000
    - DEBUG=false
  volumes:
    - ./config:/config
    - ./download:/seedbox
